name: 'Terraform Plan'
description: 'Terraform init, validate, format check and plan'
author: 'Pat Heard'

inputs:
    GITHUB_TOKEN:
      description: 'GitHub Token'
      required: true

runs:
  using: 'node12'
  main: 'dist/index.js'