name: Terraform plan
on: 
  pull_request:

jobs:
  terraform:
     runs-on: ubuntu-latest
     steps: 
      - uses: actions/checkout@v1

      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0

      - name: Terraform plan
        uses: ./.github/actions/terraform-plan
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}  