name: Test action
on: 
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        test: 
          - changes
          - no-changes
  
    steps: 
      - uses: actions/checkout@v1

      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0
          terraform_wrapper: false

      - name: Test ${{ matrix.test }}
        uses: ./
        with:
          directory: test/${{ matrix.test }}
          comment-title: Test ${{ matrix.test }}
          github-token: ${{ secrets.GITHUB_TOKEN }}