name: Test action
on: 
  pull_request:

env:
  TERRAFORM_VERSION: 1.0.0

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        test: 
          - changes
          - format-error
          - invalid
          - no-changes
  
    steps: 
      - uses: actions/checkout@v1

      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}
          terraform_wrapper: false

      - name: Test ${{ matrix.test }}
        uses: ./
        with:
          directory: test/${{ matrix.test }}
          comment-title: Test ${{ matrix.test }}
          github-token: ${{ secrets.GITHUB_TOKEN }}